# Generated by Django 4.1.5 on 2023-02-05 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createOpenProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='variable_a_predecir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('usuario', 'projectName')},
        ),
    ]
