# Generated by Django 4.1.5 on 2023-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0002_project_variable_a_predecir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modelos_ML_creados',
            field=models.FileField(blank=True, upload_to='models/MLModels'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_state',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModelosMachineLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ManyToManyField(related_name='modelo_ML', to='createOpenProject.project')),
            ],
        ),
    ]
