# Generated by Django 4.1.5 on 2023-02-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0003_project_modelos_ml_creados_project_project_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tipo_prediccion',
            field=models.CharField(blank=True, choices=[('clasificacion', 'clasificacion'), ('regresion', 'regresion')], max_length=50),
        ),
    ]
