# Generated by Django 4.1.5 on 2023-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0004_project_tipo_prediccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archivoDatosParseado',
            field=models.FileField(blank=True, upload_to='documents/datasetsProcesados/'),
        ),
    ]
