# Generated by Django 4.1.5 on 2023-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0005_project_archivodatosparseado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archivoDatosParseado',
        ),
        migrations.AddField(
            model_name='project',
            name='tiposDatosProcesados',
            field=models.FileField(blank=True, upload_to='documents/tiposDatosProcesados/'),
        ),
    ]
