# Generated by Django 4.1.5 on 2023-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0006_remove_project_archivodatosparseado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archivoDatosNA',
            field=models.FileField(blank=True, upload_to='documents/datasetsProyectosProcesados/'),
        ),
    ]
