# Generated by Django 4.1.5 on 2023-02-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0007_project_archivodatosna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modelos_ML_creados',
        ),
        migrations.DeleteModel(
            name='ModelosMachineLearning',
        ),
    ]
