# Generated by Django 4.1.5 on 2023-02-22 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0008_remove_project_modelos_ml_creados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version_datos_a_usar',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
