# Generated by Django 4.1.5 on 2023-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOpenProject', '0009_project_version_datos_a_usar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tipos_de_modelos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
