# Generated by Django 4.1.7 on 2023-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "createOpenProject",
            "0011_project_preprocesado_project_test_val_split_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tipos_de_modelos",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
