# Generated by Django 4.1.7 on 2023-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createOpenProject", "0013_project_treat_na_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="columnas_originales",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
