# Generated by Django 4.1.7 on 2023-03-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crearModelos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelosmachinelearning",
            name="supports_y_ohe",
            field=models.BooleanField(default=False),
        ),
    ]
