# Generated by Django 4.1.7 on 2023-03-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crearModelos", "0002_modelosmachinelearning_supports_y_ohe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelosmachinelearning",
            old_name="balanced_accuracy",
            new_name="metrica_valorar",
        ),
    ]
