# Generated by Django 4.1.7 on 2023-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crearModelos",
            "0003_rename_balanced_accuracy_modelosmachinelearning_metrica_valorar",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modelosmachinelearning",
            name="ensemble_models_made",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
