# Generated by Django 4.1.7 on 2023-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crearModelos", "0004_modelosmachinelearning_ensemble_models_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelosmachinelearning",
            name="ensemble_model",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
