# Generated by Django 4.1.7 on 2023-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crearModelos", "0006_alter_modelosmachinelearning_ensemble_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelosmachinelearning",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
